Repository vlayer-xyz/vlayer, pull requests merged in 2025-06, with the labels that each got.

#2439 ci: add timeouts to jobs with potentially hanging bun install
  .github/workflows/release.yaml
Labels: Ops

#2441 fix: remove obsolete traces of VITE_PRIVATE_KEY
  examples/simple-email-proof/vlayer/deploy.ts
  examples/simple-teleport/vlayer/deploy.ts
  examples/simple-time-travel/vlayer/deploy.ts
  examples/simple-web-proof/vlayer/deploy.ts
  packages/sdk/src/config/filterOverrides.test.ts
Labels: Ops

#2445 feat(call_server): parse config from file
  Cargo.lock
  Cargo.toml
  ansible/group_vars/provers.yml
  ansible/roles/prover/templates/vlayer.service.j2
  bash/run_services/config.sh
  bash/run_services/lib.sh
  book/src/appendix/architecture/prover.md
  book/src/appendix/contributing/rust.md
  book/src/getting-started/dev-and-production.md
  docker/call_server/config.toml
  docker/call_server/service.yaml
  docker/jwt/call_server/config.toml
  docker/jwt/call_server/service.yaml
  rust/cli/src/commands/jwt.rs
  rust/common/src/cli.rs
  rust/jwt/Cargo.toml
  rust/jwt/src/lib.rs
  rust/server_utils/src/jwt/axum.rs
  rust/server_utils/src/jwt/cli.rs
  rust/server_utils/src/proof_mode.rs
  rust/services/call/host/src/host/builder.rs
  rust/services/call/server/Cargo.toml
  rust/services/call/server/src/main.rs
  rust/services/call/server/src/version.rs
  rust/services/call/server_lib/Cargo.toml
  rust/services/call/server_lib/src/cli.rs
  rust/services/call/server_lib/src/config.rs
  rust/services/call/server_lib/src/gas_meter.rs
  rust/services/call/server_lib/src/handlers/v_call.rs
  rust/services/call/server_lib/src/handlers/v_call/types.rs
  rust/services/call/server_lib/src/lib.rs
Labels: Ops

#2444 feat: Reduce number of files created for benchmarking
  rust/zkvm-benchmarks/benchmarks/build.rs
  rust/zkvm-benchmarks/benchmarks/src/benchmarks/precompiles/json.rs
  rust/zkvm-benchmarks/benchmarks/src/build_utils.rs
Labels: Ethereum

#2458 chore(ansible): update other provers to trim API keys
  ansible/host_vars/stable_fake_prover.yml
  ansible/host_vars/stable_prod_prover.yml
Labels: Ops

#2456 fix: `jsonGetFloatAsInt` not present in `WebLib`
  contracts/vlayer/src/WebProof.sol
  contracts/vlayer/test/vlayer/WebLib.t.sol
Labels: Ethereum

#2460 ci: Notify PagerDuty on failed post-release tests
  .github/workflows/test_release.yaml
Labels: Ops

#2464 fix: trigger test nightly release
  .github/workflows/test_release.yaml
Labels: Web

#2462 book: update prover section
  book/src/advanced/prover.md
Labels: documentation, DevEx

#2468 chore(call_server): use custom serde deserializer for seq of string *or* struct
  rust/services/call/server/src/main.rs
  rust/services/call/server_lib/src/config.rs
Labels: Ops

#2465 fix: redirect step in extension
  packages/browser-extension/src/components/molecules/StepActions/Redirect/RedirectStepActions.tsx
  packages/sdk/src/api/webProof/steps/index.ts
Labels: Web

#2466 chore: rename `spec` field in `Benchmark` to `proverSpec`
  packages/gas-benchmarks/README.md
  packages/gas-benchmarks/src/bench.ts
  packages/gas-benchmarks/src/benches/arith_ops.ts
  packages/gas-benchmarks/src/benches/noop.ts
  packages/gas-benchmarks/src/benches/noop_with_calldata.ts
  packages/gas-benchmarks/src/types.ts
Labels: Ethereum

#2475 chore(labels): update labels to reflect new team structure
  .github/teams.yml
Labels: Protocol

#2477 chore: bump r0vm to 2.1.0
  .github/actions/risc0/action.yml
  Cargo.lock
  Cargo.toml
  ansible/group_vars/all.yml
  bash/lib/e2e.sh
  bash/test-release-local-prover.sh
  bash/test-release-remote-prover.sh
  book/src/appendix/contributing/rust.md
  book/src/appendix/contributing/upgrading_risc0.md
  contracts/fixtures/remappings.txt
  contracts/vlayer/foundry.toml
  contracts/vlayer/remappings.txt
  contracts/vlayer/soldeer.lock
  contracts/vlayer/src/MainnetStableDeployment.sol
  contracts/vlayer/src/TestnetStableDeployment.sol
  contracts/vlayer/src/proof_verifier/FakeProofVerifier.sol
  contracts/vlayer/src/proof_verifier/Groth16ProofVerifier.sol
  contracts/vlayer/src/proof_verifier/ProofVerifierBase.sol
  contracts/vlayer/test/Verifier.t.sol
  contracts/vlayer/test/helpers/Groth16VerifierSelector.sol
  contracts/vlayer/test/helpers/TestHelpers.sol
  contracts/vlayer/test/integration/ProofVerifier.t.sol
  contracts/vlayer/test/proof_verifier/FakeProofVerifier.t.sol
  contracts/vlayer/test/proof_verifier/Groth16ProofVerifier.t.sol
  contracts/vlayer/test/proof_verifier/ProofVerifier.t.sol
  contracts/vlayer/test/proof_verifier/ProofVerifierFactory.t.sol
  contracts/vlayer/test/proof_verifier/ProofVerifierRouter.t.sol
  docker/call_server/Dockerfile
  docker/chain_worker/Dockerfile
  examples/remappings.txt
  flake.nix
  nix/risc0.nix
  rust/cli/config.toml
  rust/cli/src/commands/init.rs
  rust/cli/src/config.rs
  rust/guest_wrapper/artifacts/chain_guest/CHANGELOG.md
  rust/guest_wrapper/artifacts/chain_guest/elf_id
  rust/guest_wrapper/artifacts/chain_guest/elf_id_history
  rust/guest_wrapper/risc0_call_guest/Cargo.lock
  rust/guest_wrapper/risc0_call_guest/Cargo.toml
  rust/guest_wrapper/risc0_chain_guest/Cargo.lock
  rust/guest_wrapper/risc0_chain_guest/Cargo.toml
  rust/services/call/seal/src/lib.rs
  rust/zkvm-benchmarks/runner/risc0_guest/Cargo.lock
  rust/zkvm-benchmarks/runner/risc0_guest/Cargo.toml
Labels: Protocol

#2482 ci: Remove Base from testnet imageid management
  bash/verifiers_management/push-testnet-image-id.sh
Labels: Protocol

#2421 fix: gentle handle tx rejection
  examples/simple-email-proof/vlayer/src/pages/mintNFT/Presentational.tsx
  examples/simple-email-proof/vlayer/src/shared/hooks/useEmailProofVerification.ts
  examples/simple-teleport/vlayer/src/pages/confirmMint/index.tsx
  examples/simple-web-proof/vlayer/src/components/organisms/MintStep/Container.tsx
Labels: bug, DevEx

#2484 feat: Prune elf id history
  bash/check-elf-id.sh
  book/src/appendix/contributing/upgrading_risc0.md
  rust/guest_wrapper/artifacts/chain_guest/CHANGELOG.md
  rust/guest_wrapper/artifacts/chain_guest/elf_id
  rust/guest_wrapper/artifacts/chain_guest/elf_id_history
  rust/guest_wrapper/build_utils/src/chain_guest_id.rs
  rust/guest_wrapper/build_utils/src/risc0_builder.rs
Labels: Protocol

#2488 chore(version): bump version to 1.2.0
  Cargo.lock
  rust/version/Cargo.toml
Labels: Protocol

#2491 fix: Add `--build` flag to devnet
  examples/kraken-web-proof/vlayer/package.json
  examples/simple-email-proof/vlayer/package.json
  examples/simple-teleport/vlayer/package.json
  examples/simple-time-travel/vlayer/package.json
  examples/simple-web-proof/vlayer/package.json
  examples/simple/vlayer/package.json
Labels: Protocol

#2493 Remove from book outdated extension mentions
  book/src/SUMMARY.md
  book/src/appendix/architecture/releasing.md
  book/src/appendix/contributing/extension.md
  book/src/appendix/contributing/overview.md
Labels: Vouch

#2503 ci: Update production backpropagation
  ansible/host_vars/stable_prod_chain_service.yml
Labels: Protocol

#2500 Change download extension paths
  .github/actions/build-extension/action.yml
  .github/actions/download-vouch-extension-release/action.yaml
  .github/actions/test-e2e-web-apps-opsepolia/action.yaml
  .github/actions/test-e2e-web-apps/action.yaml
  .github/workflows/deploy_simple_web_proof.yaml
  .github/workflows/test_e2e_web_flow.yaml
  .github/workflows/test_release.yaml
  bash/test-release-remote-prover.sh
  examples/simple-web-proof/vlayer/tests/config.ts
  packages/playwright-tests/config.ts
Labels: Vouch

#2506 Add files copied to vouch to codeowners
  .github/CODEOWNERS
Labels: Vouch

#2509 fix: simple email proof example eml
  examples/simple-email-proof/test/vlayer/EmailDomainProver.t.sol
  examples/simple-email-proof/testdata/verify_vlayer.eml
  examples/simple-email-proof/vlayer/tests/EmailProof.spec.ts
Labels: DevEx
