Repository vlayer-xyz/vlayer, pull requests merged in 2025-05, with the labels that each got.

#2374 fix(email example): fix block explorer url
  examples/simple-email-proof/vlayer/src/pages/success/index.tsx
Labels: Web

#2380 fix(dns-server): add version to CLI args
  Cargo.lock
  rust/services/dns/server/Cargo.toml
  rust/services/dns/server/src/cli.rs
Labels: Ops

#2382 feat: add workflow to prepare release pull requests
  .github/workflows/release_prepare_pr.yaml
Labels: Web

#2372 Link to github inside e2e test docs
  book/src/appendix/e2e-tests/e2e-test-setup.md
Labels: Ethereum

#2387 Add gas price checker
  Cargo.lock
  Cargo.toml
  rust/gas_price_checker/Cargo.toml
  rust/gas_price_checker/README
  rust/gas_price_checker/src/main.rs
Labels: Ethereum

#2358 fix(extension): countdown display [ENGA-674]
  packages/browser-extension/src/components/molecules/StepActions/Notarize/NotarizeStepActions.hooks.tsx
  packages/browser-extension/src/components/molecules/StepActions/Notarize/NotarizeStepActions.test.tsx
  packages/browser-extension/src/components/molecules/StepActions/Notarize/RedirectCallout.test.tsx
  packages/browser-extension/src/components/molecules/StepActions/Notarize/RedirectCallout.tsx
  packages/playwright-tests/extension.full.get.spec.ts
  packages/playwright-tests/pom/extension.ts
Labels: Web

#2390 Improve Host errors
  contracts/vlayer/test/vlayer/RegexLib.t.sol
  contracts/vlayer/test/vlayer/WebProofLib.t.sol
  examples/simple-web-proof/test/vlayer/WebProofProver.t.sol
  examples/simple-web-proof/vlayer/prove.ts
  rust/services/call/host/src/host.rs
  rust/services/call/host/src/host/builder.rs
  rust/services/call/host/src/host/error.rs
  rust/services/call/host/src/host/error/preflight.rs
  rust/services/call/host/src/host/tests/preflight.rs
  rust/services/call/host/src/lib.rs
  rust/services/call/server_lib/src/gas_meter.rs
  rust/services/call/server_lib/src/handlers/v_call.rs
  rust/services/call/server_lib/src/handlers/v_call/types.rs
  rust/services/call/server_lib/src/metrics.rs
  rust/services/call/server_lib/src/preflight.rs
  rust/services/call/server_lib/src/proof.rs
  rust/services/call/server_lib/src/proving.rs
  rust/services/call/server_lib/tests/integration_tests.rs
Labels: Ethereum

#2364 Add liveliness tests for `AnchorStateRegistry`
  Cargo.lock
  Cargo.toml
  clippy.toml
  rust/chain/chain_specs.toml
  rust/guest_wrapper/artifacts/chain_guest/CHANGELOG.md
  rust/guest_wrapper/artifacts/chain_guest/elf_id
  rust/guest_wrapper/artifacts/chain_guest/elf_id_history
  rust/services/call/anchor_status/Cargo.toml
  rust/services/call/anchor_status/src/main.rs
  rust/services/call/db/Cargo.toml
  rust/services/call/db/src/lib.rs
  rust/services/call/db/src/proof.rs
  rust/services/call/db/src/provider.rs
  rust/services/call/host/Cargo.toml
  rust/services/call/host/src/db.rs
  rust/services/call/host/src/evm_env/factory.rs
  rust/services/call/host/src/host.rs
  rust/services/call/host/src/host/error/preflight.rs
  rust/services/call/host/src/host/tests.rs
  rust/services/call/host/src/host/tests/number_of_rpc_calls.rs
  rust/services/call/host/src/host/tests/preflight.rs
  rust/services/call/host/src/host/tests/teleport.rs
  rust/services/call/host/src/host/tests/with_guest.rs
  rust/services/call/host/src/into_input.rs
  rust/services/call/host/src/lib.rs
  rust/services/call/host/src/test_harness.rs
  rust/services/call/rpc/.env.example
  rust/services/call/rpc/Cargo.toml
  rust/services/call/rpc/src/lib.rs
  rust/test_runner/Cargo.toml
  rust/test_runner/src/providers/pending_state_provider.rs
Labels: Ethereum

#2389 chore(web_prover): use builder pattern for creating NotaryConfig
  Cargo.lock
  rust/cli/src/commands/web_proof.rs
  rust/generate_fixtures/src/main.rs
  rust/web_prover/Cargo.toml
  rust/web_prover/src/lib.rs
  rust/web_prover/src/params.rs
  rust/web_prover/tests/integration_tests.rs
Labels: Ops

#2391 feat(web_prover): support JWT tokens for TLSN auth
  .github/workflows/test_int_web_prover.yaml
  Cargo.lock
  rust/cli/src/commands/web_proof.rs
  rust/web_prover/Cargo.toml
  rust/web_prover/src/notarize.rs
  rust/web_prover/src/params.rs
Labels: Ops

#2388 ci: fix incorrectly scoped restart handlers
  ansible/roles/chain_server/handlers/main.yml
  ansible/roles/chain_server/tasks/main.yml
  ansible/roles/chain_worker/handlers/main.yml
  ansible/roles/chain_worker/tasks/main.yml
Labels: Ops

#2394 Upload Gas Price Checker to AWS S3
  .github/workflows/build_gas_price_checker.yaml
  .github/workflows/test_e2e_bonsai_opsepolia.yaml
  rust/gas_price_checker/README
Labels: Ethereum

#2392 fix(email example): handling errors from preverify [ENGA-703]
  examples/simple-email-proof/vlayer/src/shared/errors/appErrors.ts
  examples/simple-email-proof/vlayer/src/shared/hooks/useEmailProofVerification.ts
Labels: Web

#2378 Refactor chain synchronisation mechanism
  bun.lock
  examples/simple-email-proof/vlayer/package.json
  examples/simple-email-proof/vlayer/src/shared/errors/appErrors.ts
  examples/simple-email-proof/vlayer/src/shared/hooks/useEmailProofVerification.ts
  examples/simple-teleport/vlayer/src/shared/errors/appErrors.ts
  examples/simple-teleport/vlayer/src/shared/hooks/useProver.ts
  examples/simple-time-travel/vlayer/src/shared/errors/appErrors.ts
  examples/simple-time-travel/vlayer/src/shared/hooks/useProver.ts
  examples/simple-web-proof/vlayer/package.json
  examples/simple-web-proof/vlayer/src/App.tsx
  examples/simple-web-proof/vlayer/src/components/organisms/MintStep/Container.tsx
  examples/simple-web-proof/vlayer/src/errors.ts
  examples/simple-web-proof/vlayer/src/hooks/useTwitterAccountProof.ts
  packages/sdk-hooks/src/index.ts
  packages/sdk-hooks/src/useChain/useChain.anvil.test.tsx
  packages/sdk-hooks/src/useChain/useChain.sepolia.test.tsx
  packages/sdk-hooks/src/useChain/useChain.ts
  packages/sdk-hooks/src/useSyncChain/useSyncChain.test.tsx
  packages/sdk-hooks/src/useSyncChain/useSyncChain.ts
Labels: Web

#2400 feat: Export redaction types from SDK
  packages/sdk/src/index.ts
  packages/web-proof-commons/types/redaction.ts
Labels: Email

#2403 fix(book): update wsproxy protocol
  book/src/getting-started/dev-and-production.md
Labels: Ops

#2404 ci: remove obsolete SecOps from codeowners
  .github/CODEOWNERS
Labels: Ops

#2406 fix: Revert "Refactor chain synchronisation mechanism"
  bun.lock
  examples/simple-email-proof/vlayer/package.json
  examples/simple-email-proof/vlayer/src/shared/errors/appErrors.ts
  examples/simple-email-proof/vlayer/src/shared/hooks/useEmailProofVerification.ts
  examples/simple-teleport/vlayer/src/shared/errors/appErrors.ts
  examples/simple-teleport/vlayer/src/shared/hooks/useProver.ts
  examples/simple-time-travel/vlayer/src/shared/errors/appErrors.ts
  examples/simple-time-travel/vlayer/src/shared/hooks/useProver.ts
  examples/simple-web-proof/vlayer/package.json
  examples/simple-web-proof/vlayer/src/App.tsx
  examples/simple-web-proof/vlayer/src/components/organisms/MintStep/Container.tsx
  examples/simple-web-proof/vlayer/src/errors.ts
  examples/simple-web-proof/vlayer/src/hooks/useTwitterAccountProof.ts
  packages/sdk-hooks/src/index.ts
  packages/sdk-hooks/src/useChain/useChain.anvil.test.tsx
  packages/sdk-hooks/src/useChain/useChain.sepolia.test.tsx
  packages/sdk-hooks/src/useChain/useChain.ts
  packages/sdk-hooks/src/useSyncChain/useSyncChain.test.tsx
  packages/sdk-hooks/src/useSyncChain/useSyncChain.ts
Labels: Web

#2399 feat(sdk): export mid-level api with direct access to prover calls
  bun.lock
  examples/simple-email-proof/vlayer/package.json
  examples/simple-email-proof/vlayer/playwright.config.ts
  examples/simple-teleport/vlayer/package.json
  examples/simple-teleport/vlayer/playwright.config.ts
  examples/simple-time-travel/vlayer/package.json
  examples/simple-time-travel/vlayer/playwright.config.ts
  examples/simple-web-proof/vlayer/package.json
  examples/simple-web-proof/vlayer/playwright.config.ts
  packages/browser-extension/package.json
  packages/gas-benchmarks/src/bench.ts
  packages/playwright.config.ts
  packages/sdk/package.json
  packages/sdk/src/api/prover/index.ts
  packages/sdk/src/api/prover/prover.ts
  packages/sdk/src/api/prover/v_call.ts
  packages/sdk/src/api/prover/v_getProofReceipt.ts
  packages/sdk/src/api/prover/v_versions.ts
  packages/sdk/src/config/deploy.ts
Labels: Ops

#2401 fix: teleport explorer ui
  examples/simple-teleport/vlayer/src/pages/success/index.tsx
Labels: bug, DevEx

#2409 Remove hardcoded faucet
  bun.lock
  examples/simple-teleport/vlayer/package.json
  examples/simple-teleport/vlayer/src/pages/confirmMint/index.tsx
Labels: Web

#2395 feat: add workflow to check guest ID on mainnet
  .github/actions/publish-image-id-onchain/action.yml
  .github/actions/verify-image-id-onchain/action.yml
  bash/verifiers_management/push-testnet-image-id.sh
  bash/verifiers_management/verify-mainnet-image-id.sh
  contracts/vlayer/script/ImageIdAdministration.s.sol
Labels: Web

#2407 chore(ci): merge similar workflows into one
  .github/actions/test-e2e-web-apps/action.yaml
  .github/workflows/test_e2e_web_apps.yaml
  .github/workflows/test_e2e_web_apps_jwt.yaml
Labels: Ops

#2410 fix(config): update Ethereum RPC endpoint
  contracts/vlayer/foundry.toml
Labels: Web

#2413 ci: Optimize `vlayerup` in chain services installation
  ansible/roles/chain_server/handlers/main.yml
  ansible/roles/chain_server/tasks/main.yml
  ansible/roles/chain_worker/handlers/main.yml
  ansible/roles/chain_worker/tasks/main.yml
Labels: Ops

#2402 Add scripting and activeTab permissions to extension
  packages/browser-extension/src/manifest.json
Labels: Email

#2414 feat(extension): send message to browser when step was completed
  packages/browser-extension/src/background.ts
  packages/browser-extension/src/hooks/useNotifyOnStepCompleted.test.ts
  packages/browser-extension/src/hooks/useNotifyOnStepCompleted.ts
  packages/browser-extension/src/hooks/useSteps.test.ts
  packages/browser-extension/src/hooks/useSteps.ts
  packages/web-proof-commons/types/message.ts
Labels: Email

#2398 feat(extension): add userStepAction to extension
  packages/browser-extension/src/background.ts
  packages/browser-extension/src/components/atoms/Image.module.css
  packages/browser-extension/src/components/atoms/Image.tsx
  packages/browser-extension/src/components/molecules/Step.tsx
  packages/browser-extension/src/components/molecules/StepActions/StepActions.tsx
  packages/browser-extension/src/components/molecules/StepActions/UserAction/UserActionStepActions.tsx
  packages/browser-extension/src/components/molecules/StepActions/UserAction/index.ts
  packages/browser-extension/src/constants/step.ts
  packages/browser-extension/src/hooks/useSteps.test.data.ts
  packages/browser-extension/src/hooks/useSteps.test.helpers.ts
  packages/browser-extension/src/hooks/useSteps.test.ts
  packages/browser-extension/src/hooks/useSteps.ts
  packages/browser-extension/src/lib/activeTabContext.ts
  packages/browser-extension/vitest/setup.ts
  packages/extension-hooks/src/index.ts
  packages/extension-hooks/src/useIntervalCalls.test.ts
  packages/extension-hooks/src/useIntervalCalls.ts
  packages/sdk/src/api/webProof/steps/index.ts
  packages/sdk/src/api/webProof/steps/userAction.ts
  packages/web-proof-commons/types/message.ts
Labels: Email

#2425 feat: Benchmarks refactor
  rust/zkvm-benchmarks/benchmarks/src/lib.rs
  rust/zkvm-benchmarks/runner/src/runner.rs
Labels: Ethereum

#2422 feat: Include `chain_id` in `ChainServiceNotAvailable` error
  rust/services/call/engine/src/verifier/time_travel.rs
Labels: Ethereum

#2426 fix(cli): add default headers only if not specified by the user
  rust/web_prover/src/notarize.rs
  rust/web_prover/tests/integration_tests.rs
Labels: Ops

#2423 feat: Enable teleport example on sepolia
  .github/actions/test-e2e/action.yaml
  .github/workflows/test_e2e_sepolias.yaml
  bash/run-services.sh
  bash/run_services/lib.sh
Labels: Ethereum

#2431 fix: Remove code duplication
  packages/web-proof-commons/types/redaction.ts
Labels: Web

#2433 chore(ansible): configure GAS_METER_API_KEY from env vars
  ansible/roles/prover/templates/vlayer.service.j2
Labels: Ops

#2420 fix(CI): remove flakiness in extension playwright tests [ENGA-740]
  packages/playwright-tests/extension.full.get.spec.ts
  packages/playwright-tests/extension.full.put.spec.ts
Labels: Web

#2233 feat: upgrade tlsn to v10
  Cargo.lock
  Cargo.toml
  bun.lock
  contracts/vlayer/testdata/web_proof.json
  contracts/vlayer/testdata/web_proof_invalid_notary_pub_key.json
  contracts/vlayer/testdata/web_proof_missing_part.json
  docker/notary-config/config.yaml
  docker/notary-server/Dockerfile
  docker/web-proof/docker-compose-release.yaml
  examples/simple-web-proof/test/vlayer/WebProofProver.t.sol
  examples/simple-web-proof/testdata/web_proof.json
  examples/simple-web-proof/testdata/web_proof_invalid_notary_pub_key.json
  packages/browser-extension/package.json
  rust/generate_fixtures/src/main.rs
  rust/guest_wrapper/risc0_call_guest/Cargo.lock
  rust/services/call/server_lib/tests/integration_tests.rs
  rust/web_proof/src/snapshots/web_proof__web_proof__tests__received_response.snap
  rust/web_proof/testdata/web_proof.json
  rust/web_proof/testdata/web_proof_all_redaction_types.json
  rust/web_proof/testdata/web_proof_bad_signature.json
  rust/web_proof/testdata/web_proof_identity_name_changed.json
  rust/web_proof/testdata/web_proof_request_header_partial_redaction.json
  rust/web_proof/testdata/web_proof_request_url_partial_redaction.json
  rust/web_proof/testdata/web_proof_response_header_partial_redaction.json
  rust/web_proof/testdata/web_proof_response_json_partial_redaction.json
  rust/web_prover/src/lib.rs
  rust/zkvm-benchmarks/runner/risc0_guest/Cargo.lock
Labels: Web

#2434 docs: improve docs according to Antek feedback
  book/book.toml
  book/src/SUMMARY.md
  book/src/advanced/dev-and-production.md
  book/src/advanced/verifier.md
  book/src/appendix/contributing/overview.md
  examples/simple/src/vlayer/SimpleProver.sol
Labels: documentation, DevEx

#2437 ci: add worldchain RPC URLs to provers
  ansible/host_vars/nightly_fake_prover.yml
  ansible/host_vars/stable_fake_prover.yml
  ansible/host_vars/stable_prod_prover.yml
Labels: Ops
